# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Idea Barrel CI

on:
  push:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm test


    discord:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/staging'
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: 'https://discordapp.com/channels/@me/674884605131751438/819631666929991721'
      uses: Ilshidur/action-discord@master
      with:
       args: 'Staging has been updated - please pull!'

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Zip Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'ideabarrel.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
